export const LOAD_ALL_PRODUCTS_SUCCESS = 'LOAD_ALL_PRODUCTS_SUCCESS';
export const LOAD_ALL_PRODUCTS_FAILURE = 'LOAD_ALL_PRODUCTS_FAILURE';


export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_FAILURE = 'GET_MOVIE_LIST_FAILURE';

export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DETAIL_FAILURE = 'GET_MOVIE_DETAIL_FAILURE';



export const GET_PAGES = 'GET_PAGES';

